#===Common===
explicit_timeout=15
auto_screenshot=true
driver_type=mobile
selenium_url=http://127.0.0.1:4723/

#===Android===
#capabilities.platformName=Android
#capabilities.deviceName=Pixel 6 Pro
#capabilities.automationName=UiAutomator2
#capabilities.app=/Users/ivanchelombitko/IdeaProjects/SauceLabs/Android.SauceLabs.Mobile.Sample.app.2.7.1.apkAndroid.SauceLabs.Mobile.Sample.app.2.7.1.apk
#capabilities.appPackage=com.swaglabsmobileapp
#capabilities.appActivity=com.swaglabsmobileapp.MainActivity

#===iOS===
capabilities.platformName=iOS
capabilities.deviceName=iPhone 17
capabilities.platformVersion=26.5
capabilities.automationName=XCUITest
capabilities.app=/Users/ivanchelombitko/IdeaProjects/SauceLabs/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.7.1.zip
capabilities.appium:usePrebuiltWDA=true